import { chromium } from 'playwright';
const CHROME = '/root/.cache/ms-playwright/chromium-1234/chrome-linux/chrome';
const browser = await chromium.launch({ headless: true, executablePath: CHROME, args: ['--no-sandbox', '--disable-dev-shm-usage'] });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
const logs = [];
page.on('console', (m) => { const t = m.text(); if (t.includes('[erase]')) logs.push(t); });
await page.goto('http://localhost:8787/');
await page.waitForSelector('.welcome', { timeout: 8000 });
await page.evaluate(() => { localStorage.clear(); localStorage.setItem('cs.helpSeen', '1'); });
await page.reload();
await page.waitForSelector('.welcome');
await page.click('text=＋ 新建项目');
await page.click('.type-card:has-text("小说")');
await page.click('.modal-actions .btn.primary');
await page.waitForSelector('.canvas-wrap');
await page.waitForTimeout(500);
const wb = await page.locator('.canvas-wrap').boundingBox();
await page.click('.zc-fab'); await page.waitForTimeout(300);
await page.click('.zc-tool:has-text("画笔")'); await page.waitForTimeout(300);
// 画长线
await page.mouse.move(wb.x + 200, wb.y + 400); await page.mouse.down();
await page.mouse.move(wb.x + 500, wb.y + 400, { steps: 10 }); await page.mouse.up();
await page.waitForTimeout(300);
console.log('画后笔画数:', await page.locator('.annotation-g').count());
// 切橡皮，滑动擦中间段
await page.click('.zc-tool:has-text("橡皮")'); await page.waitForTimeout(300);
await page.mouse.move(wb.x + 300, wb.y + 400); await page.mouse.down();
await page.mouse.move(wb.x + 380, wb.y + 400, { steps: 5 }); await page.mouse.up();
await page.waitForTimeout(400);
console.log('擦后笔画数:', await page.locator('.annotation-g').count());
console.log('--- 日志 ---');
logs.forEach((l) => console.log(l));
await browser.close();
process.exit(0);