import { chromium } from 'playwright';
const CHROME = '/root/.cache/ms-playwright/chromium-1234/chrome-linux/chrome';
const browser = await chromium.launch({ headless: true, executablePath: CHROME, args: ['--no-sandbox'] });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 800 } })).newPage();
const logs=[]; page.on('console',m=>logs.push(m.type()+':'+m.text().slice(0,90))); page.on('pageerror',e=>logs.push('err:'+String(e).slice(0,120)));
await page.goto('http://localhost:8787/');
await page.waitForSelector('.welcome',{timeout:8000});
await page.evaluate(()=>{localStorage.clear();localStorage.setItem('cs.helpSeen','1');});
await page.reload(); await page.waitForSelector('.welcome');
await page.click('text=＋ 新建项目'); await page.waitForTimeout(300);
const types = await page.evaluate(()=>[...document.querySelectorAll('.type-card')].map(t=>t.textContent.trim()).join('|'));
console.log('类型卡:', types.slice(0,60));
await page.click('.type-card:has-text("小说")');
const btns = await page.evaluate(()=>[...document.querySelectorAll('.modal-actions button')].map(b=>b.textContent.trim()));
console.log('模态动作按钮:', JSON.stringify(btns));
await page.click('.modal-actions .btn.primary');
await page.waitForTimeout(3000);
const state = await page.evaluate(()=>({ wrap: !!document.querySelector('.canvas-wrap'), cardN: document.querySelectorAll('.card').length, body: document.body.innerText.slice(0,40), proj: localStorage.getItem('cs.projects')?.slice(0,30) }));
console.log('状态:', JSON.stringify(state));
console.log('logs:', logs.slice(0,12).join(' || '));
await browser.close();